### GENERAL SETTINGS ###
# Exclude folders from the build
exclude:
  - _hidden

# Site settings
title: ESN DATA
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: /solid-jekyll-BIA #important: start with /
url: https://stefch86.github.io/solid-jekyll-BIA/

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: linkedin
    url: https://www.linkedin.com/in/stephane-chaillie/

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - New York,
    - United States.
email: steph.chaillie@gmail.com
tel: +33 628525778


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Stephane Chaillie
    position: SENIOR BUSINESS INTELLIGENCE ANALYST
    text: A highly proficient data expert with a decade of experience, adept at leveraging advanced data management tools and technologies to optimize workflows and ensure organizational efficiency. You can follow my experiences within ESN DATA through my Tableau Dashboard <a href="https://public.tableau.com/views/Dashboard_CV_v11/Tableaudebord1?:language=fr-FR&:display_count=n&:origin=viz_share_link" target="_blank">here</a>.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:steph.chaillie@gmail.com
      # - title: twitter
      #   url: http://twitter.com/handle
      - title: linkedin
        url: https://www.linkedin.com/in/stephane-chaillie/
# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "ESN Data, a Digital Services Company that provides Experts all around the worlds as a Business Intelligence consultant"
